### ISSUE TITLE
Rights are changed during dockergento start

### ISSUE THREAD

**Issue by TonySma** [ModestCoders/magento2-dockergento#30]
Hi, 

After running dockergento start, files owners changed. 
How i can fix this? 

![image](https://user-images.githubusercontent.com/6605868/48314632-637c9c00-e5cc-11e8-9ae3-43aa67a1ff54.png)
![image](https://user-images.githubusercontent.com/6605868/48314643-8eff8680-e5cc-11e8-9f53-571e782e4b64.png)

Thank for your help. 
Tony

**Comment by jalogut** [comment]
Hi @TonySma 

I guess you are on Linux, right? Because I did not face this problem on Mac. I think the problem comes from the php entrypoint here:

- 
https://github.com/ModestCoders/dockerfiles/blob/master/php/7.1-fpm/docker-entrypoint.sh#L4

During the spin up of containers we need to ensure that user `app` owns the project files. This user has id `1000` inside images and is the user used by nginx and phpfpm. In Mac there is no problem with that because of a virtualization layer that separates host and container, so permission are not changed in the host. I see now that it doesn`t seem to be same in Linux. It seems that if permissions change inside containers it also affects your host permissions. You are seeing `1000` because you might not have any user with this uid.

To be honest I am not sure if there is a way to avoid that in linux with some docker configuration or if that is normal. I would try to get some more info about that. Until then, I would also appreciate if you could also help us to find a solution for that ;)

**Comment by ihor-sviziev** [comment]
@jalogut as example for Linux we could use different image without changing permissions

**Comment by ihor-sviziev** [comment]
Not sure if it will be easy to add support for different user IDs, probably we can add it as "limitations"

**Comment by jalogut** [comment]
Hi @TonySma and @ihor-sviziev 

I just created PR https://github.com/ModestCoders/magento2-dockergento/pull/40 to match `uid` and `gid` on host when the containers start.

Until it gets merged, we would appreciate if you could checkout the branch `fix-perms` and test it on your computers?

You only need to execute `dockergento start`. Then the script checks the `uids` and correct them if they are not matching.  

Thanks

**Comment by danielozano** [comment]
I'm closing this issue, it should be solved since #40 was merged.
