### ISSUE TITLE
How to increase memory of php?

### ISSUE THREAD

**Issue by winston-magemojo** [ModestCoders/magento2-dockergento#34]
Hi, 

I am playing with large csv imports - on importing a 20MB 1 000 000 row csv I get

```
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.Command exited with non-zero status 255
```

What is the best way to change php.ini settings?

Thanks!

**Comment by danielozano** [comment]
Hi @winston-magemojo!

The best way is to implement your own Dockerfile, and copy custom .ini config file into the container.
By default our docker php images implement this configuration:
```
memory_limit = 2G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

upload_max_filesize = 20M
post_max_size = 20M
```

So I recommend you to modify your specific `docker-compose.dev.linux.yml` or `docker-compose.dev.mac.yml` and add this lines in the `phpfpm` service `phpfpm`, instead of the `image` tag:
```yml
  phpfpm:
    build: ./config/dockergento/phpfpm/ # here just add the route where your new Dockerfile is going to be placed
```

Then create the Dockerfile with the following content:
```
FROM modestcoders/php:7.1-fpm-1 // again here add the version of the image you are using (7.2 for example)

USER root

COPY ./conf/*.ini /usr/local/etc/php/conf.d/  // here the route where your .ini files is going to be placed
```

Then just create your own .ini file (for example custom-config.ini) adding your own memory setting: `memory_limit=-1` or whatever you want!

After that you will've to rebuild the containers with the new images, so run `dockergento rebuild`

Let me know it this explanation helps you! Thank you for giving a try to the tool!

**Comment by WinstonN** [comment]
Hello @danielozano 

Thank you very much for this helpful guide!

This worked very well!
I did notice that xdebug was not working with this new setup, and I had a look at https://github.com/ModestCoders/dockerfiles/blob/master/php/7.2-fpm/Dockerfile

..and decided to use that config directory in my docker file too

My Dockerfile now looks iike

```
# build ontop of the PHP 7.2 image
FROM modestcoders/php:7.2-fpm-1

USER root

# add ini files in a path relative to this Dockerfile
COPY conf/www.conf /usr/local/etc/php-fpm.d/
COPY conf/php.ini /usr/local/etc/php/
COPY conf/xdebug.ini /usr/local/etc/php/conf.d/
COPY conf/php-fpm.conf /usr/local/etc/

USER app:app
```

Thank you very much again for being so helpful, and I do really enjoy using dockergento <3

**Comment by danielozano** [comment]
Hi @winston-magemojo, I'm glad this helped you!

Probably the x-debug problem was because of this line `COPY ./conf/*.ini /usr/local/etc/php/conf.d/`. My fault! You should've pointed you to use another custom file name instead of the original!

Regards! Thank you so much for using the tool!
