### ISSUE TITLE
FEATURE: Mage2run

### ISSUE THREAD

**Issue by alainseys** [ModestCoders/magento2-dockergento#92]
hy is it possible to add [magerun2 ](https://github.com/netz98/n98-magerun2)to the docker compose ? and run it from dockergento ?

**Comment by danielozano** [comment]
Hi! @alainseys, If you are running it on linux, just download it at your project root and will be available inside the container. Otherwise, if you are running it on Mac, you have to add a new line at the `docker-compose.dev.mac.yml` in order to sync the file with the container `(for example adding to volumes section: - ./n98-magerun.phar:/var/www/html/n98-magerun.phar:delegated)`

Once available you will probably need to add execution permisions (chmod +x n98-magerun.phar) and then you can run it with: `dockergento exec ./n98-magerun2.phar`

**Comment by alainseys** [comment]
> Hi! @alainseys, If you are running it on linux, just download it at your project root and will be available inside the container. Otherwise, if you are running it on Mac, you have to add a new line at the `docker-compose.dev.mac.yml` in order to sync the file with the container `(for example adding to volumes section: - ./n98-magerun.phar:/var/www/html/n98-magerun.phar:delegated)`
> 
> Once available you will probably need to add execution permisions (chmod +x n98-magerun.phar) and then you can run it with: `dockergento exec ./n98-magerun2.phar`

Hy @danielozano  , thanks for the info i will try this.

**Comment by alainseys** [comment]
> Hi! @alainseys, If you are running it on linux, just download it at your project root and will be available inside the container. Otherwise, if you are running it on Mac, you have to add a new line at the `docker-compose.dev.mac.yml` in order to sync the file with the container `(for example adding to volumes section: - ./n98-magerun.phar:/var/www/html/n98-magerun.phar:delegated)`
> 
> Once available you will probably need to add execution permisions (chmod +x n98-magerun.phar) and then you can run it with: `dockergento exec ./n98-magerun2.phar`

Hy i have tried this and this solutions works for me this issue can be closed
